import React, { useState } from "react";
import { Button, Menu, MenuItem, Divider, Typography } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";

const Navbar2 = () => {

    return (
        <div className="main">
            <nav className="main__navbar">
                <ul className="main__navbar--lists">
                    <li className="main__navbar--list men">
                        <a href="#men" className="menu">
                            MEN
                        </a>

                        <div className="menu__content">
                            <div className="menu__content-lists">
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleM"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleM"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleM"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleM"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleM"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkM"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>

                    <li className="main__navbar--list women">
                        <a href="#men" className="menu">
                            WOMEN
                        </a>

                        <div className="menu__content">
                            <div className="menu__content-lists">
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleF"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkF"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>

                    <li className="main__navbar--list kids">
                        <a href="#men" className="menu">
                            KIDS
                        </a>

                        <div className="menu__content">
                            <div className="menu__content-lists">
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleK"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkK"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>

                    <li className="main__navbar--list offers">
                        <a href="#men" className="menu">
                            OFFERS
                        </a>

                        <div className="menu__content">
                            <div className="menu__content-lists">
                                <ul>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-titleO"
                                        >
                                            Topwear
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            T-Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Casual Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Formal Shirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Sweatshirts
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Sweaters
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Jackets
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Blazers {"&"} Coats
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Suits
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#"
                                            className="menu__content-lists--linkO"
                                        >
                                            Rain Jackets
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </nav>
        </div>
    );
};

export default Navbar2;
