export const ADDRESS_ADMIN_LIST_REQUEST = "ADDRESS_ADMIN_LIST_REQUEST"
export const ADDRESS_ADMIN_LIST_SUCCESS = "ADDRESS_ADMIN_LIST_SUCCESS"
export const ADDRESS_ADMIN_LIST_FAIL = "ADDRESS_ADMIN_LIST_FAIL"
export const ADDRESS_ADMIN_LIST_RESET = "ADDRESS_ADMIN_LIST_RESET"

export const ADDRESS_CREATE_REQUEST = "ADDRESS_CREATE_REQUEST"
export const ADDRESS_CREATE_SUCCESS = "ADDRESS_CREATE_SUCCESS"
export const ADDRESS_CREATE_FAIL = "ADDRESS_CREATE_FAIL"
export const ADDRESS_CREATE_RESET = "ADDRESS_CREATE_RESET"

export const ADDRESS_EDIT_REQUEST = "ADDRESS_EDIT_REQUEST"
export const ADDRESS_EDIT_SUCCESS = "ADDRESS_EDIT_SUCCESS"
export const ADDRESS_EDIT_FAIL = "ADDRESS_EDIT_FAIL"
export const ADDRESS_EDIT_RESET = "ADDRESS_EDIT_RESET"

export const ADDRESS_GET_DETAILS_REQUEST = "ADDRESS_GET_DETAILS_REQUEST";
export const ADDRESS_GET_DETAILS_SUCCESS = "ADDRESS_GET_DETAILS_SUCCESS";
export const ADDRESS_GET_DETAILS_FAIL = "ADDRESS_GET_DETAILS_FAIL";
export const ADDRESS_GET_DETAILS_RESET = "ADDRESS_GET_DETAILS_RESET";

export const ADDRESS_DELETE_REQUEST = "ADDRESS_DELETE_REQUEST";
export const ADDRESS_DELETE_SUCCESS = "ADDRESS_DELETE_SUCCESS";
export const ADDRESS_DELETE_FAIL = "ADDRESS_DELETE_FAIL";