export const BRAND_ADMIN_LIST_REQUEST = "BRAND_ADMIN_LIST_REQUEST"
export const BRAND_ADMIN_LIST_SUCCESS = "BRAND_ADMIN_LIST_SUCCESS"
export const BRAND_ADMIN_LIST_FAIL = "BRAND_ADMIN_LIST_FAIL"
export const BRAND_ADMIN_LIST_RESET = "BRAND_ADMIN_LIST_RESET"

export const BRAND_CREATE_REQUEST = "BRAND_CREATE_REQUEST"
export const BRAND_CREATE_SUCCESS = "BRAND_CREATE_SUCCESS"
export const BRAND_CREATE_FAIL = "BRAND_CREATE_FAIL"
export const BRAND_CREATE_RESET = "BRAND_CREATE_RESET"

export const BRAND_EDIT_REQUEST = "BRAND_EDIT_REQUEST"
export const BRAND_EDIT_SUCCESS = "BRAND_EDIT_SUCCESS"
export const BRAND_EDIT_FAIL = "BRAND_EDIT_FAIL"
export const BRAND_EDIT_RESET = "BRAND_EDIT_RESET"

export const BRAND_GET_DETAILS_REQUEST = "BRAND_GET_DETAILS_REQUEST";
export const BRAND_GET_DETAILS_SUCCESS = "BRAND_GET_DETAILS_SUCCESS";
export const BRAND_GET_DETAILS_FAIL = "BRAND_GET_DETAILS_FAIL";
export const BRAND_GET_DETAILS_RESET = "BRAND_GET_DETAILS_RESET";

export const BRAND_DELETE_REQUEST = "BRAND_DELETE_REQUEST";
export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
export const BRAND_DELETE_FAIL = "BRAND_DELETE_FAIL";