export const CHILD_CATEGORY_ADMIN_LIST_REQUEST = "CHILD_CATEGORY_ADMIN_LIST_REQUEST"
export const CHILD_CATEGORY_ADMIN_LIST_SUCCESS = "CHILD_CATEGORY_ADMIN_LIST_SUCCESS"
export const CHILD_CATEGORY_ADMIN_LIST_FAIL = "CHILD_CATEGORY_ADMIN_LIST_FAIL"
export const CHILD_CATEGORY_ADMIN_LIST_RESET = "CHILD_CATEGORY_ADMIN_LIST_RESET"

export const CHILD_CATEGORY_CREATE_REQUEST = "CHILD_CATEGORY_CREATE_REQUEST"
export const CHILD_CATEGORY_CREATE_SUCCESS = "CHILD_CATEGORY_CREATE_SUCCESS"
export const CHILD_CATEGORY_CREATE_FAIL = "CHILD_CATEGORY_CREATE_FAIL"
export const CHILD_CATEGORY_CREATE_RESET = "CHILD_CATEGORY_CREATE_RESET"

export const CHILD_CATEGORY_EDIT_REQUEST = "CHILD_CATEGORY_EDIT_REQUEST"
export const CHILD_CATEGORY_EDIT_SUCCESS = "CHILD_CATEGORY_EDIT_SUCCESS"
export const CHILD_CATEGORY_EDIT_FAIL = "CHILD_CATEGORY_EDIT_FAIL"
export const CHILD_CATEGORY_EDIT_RESET = "CHILD_CATEGORY_EDIT_RESET"

export const CHILD_CATEGORY_GET_DETAILS_REQUEST = "CHILD_CATEGORY_GET_DETAILS_REQUEST";
export const CHILD_CATEGORY_GET_DETAILS_SUCCESS = "CHILD_CATEGORY_GET_DETAILS_SUCCESS";
export const CHILD_CATEGORY_GET_DETAILS_FAIL = "CHILD_CATEGORY_GET_DETAILS_FAIL";
export const CHILD_CATEGORY_GET_DETAILS_RESET = "CHILD_CATEGORY_GET_DETAILS_RESET";

export const CHILD_CATEGORY_DELETE_REQUEST = "CHILD_CATEGORY_DELETE_REQUEST";
export const CHILD_CATEGORY_DELETE_SUCCESS = "CHILD_CATEGORY_DELETE_SUCCESS";
export const CHILD_CATEGORY_DELETE_FAIL = "CHILD_CATEGORY_DELETE_FAIL";