export const COLOR_ADMIN_LIST_REQUEST = "COLOR_ADMIN_LIST_REQUEST"
export const COLOR_ADMIN_LIST_SUCCESS = "COLOR_ADMIN_LIST_SUCCESS"
export const COLOR_ADMIN_LIST_FAIL = "COLOR_ADMIN_LIST_FAIL"
export const COLOR_ADMIN_LIST_RESET = "COLOR_ADMIN_LIST_RESET"

export const COLOR_CREATE_REQUEST = "COLOR_CREATE_REQUEST"
export const COLOR_CREATE_SUCCESS = "COLOR_CREATE_SUCCESS"
export const COLOR_CREATE_FAIL = "COLOR_CREATE_FAIL"
export const COLOR_CREATE_RESET = "COLOR_CREATE_RESET"

export const COLOR_EDIT_REQUEST = "COLOR_EDIT_REQUEST"
export const COLOR_EDIT_SUCCESS = "COLOR_EDIT_SUCCESS"
export const COLOR_EDIT_FAIL = "COLOR_EDIT_FAIL"
export const COLOR_EDIT_RESET = "COLOR_EDIT_RESET"

export const COLOR_GET_DETAILS_REQUEST = "COLOR_GET_DETAILS_REQUEST";
export const COLOR_GET_DETAILS_SUCCESS = "COLOR_GET_DETAILS_SUCCESS";
export const COLOR_GET_DETAILS_FAIL = "COLOR_GET_DETAILS_FAIL";
export const COLOR_GET_DETAILS_RESET = "COLOR_GET_DETAILS_RESET";

export const COLOR_DELETE_REQUEST = "COLOR_DELETE_REQUEST";
export const COLOR_DELETE_SUCCESS = "COLOR_DELETE_SUCCESS";
export const COLOR_DELETE_FAIL = "COLOR_DELETE_FAIL";