export const PARENT_CATEGORY_LIST_REQUEST = "PARENT_CATEGORY_LIST_REQUEST"
export const PARENT_CATEGORY_LIST_SUCCESS = "PARENT_CATEGORY_LIST_SUCCESS"
export const PARENT_CATEGORY_LIST_FAIL = "PARENT_CATEGORY_LIST_FAIL"
export const PARENT_CATEGORY_LIST_RESET = "PARENT_CATEGORY_LIST_RESET"

export const PARENT_CATEGORY_ADMIN_LIST_REQUEST = "PARENT_CATEGORY_ADMIN_LIST_REQUEST"
export const PARENT_CATEGORY_ADMIN_LIST_SUCCESS = "PARENT_CATEGORY_ADMIN_LIST_SUCCESS"
export const PARENT_CATEGORY_ADMIN_LIST_FAIL = "PARENT_CATEGORY_ADMIN_LIST_FAIL"
export const PARENT_CATEGORY_ADMIN_LIST_RESET = "PARENT_CATEGORY_ADMIN_LIST_RESET"

export const PARENT_CATEGORY_CREATE_REQUEST = "PARENT_CATEGORY_CREATE_REQUEST"
export const PARENT_CATEGORY_CREATE_SUCCESS = "PARENT_CATEGORY_CREATE_SUCCESS"
export const PARENT_CATEGORY_CREATE_FAIL = "PARENT_CATEGORY_CREATE_FAIL"
export const PARENT_CATEGORY_CREATE_RESET = "PARENT_CATEGORY_CREATE_RESET"

export const PARENT_CATEGORY_EDIT_REQUEST = "PARENT_CATEGORY_EDIT_REQUEST"
export const PARENT_CATEGORY_EDIT_SUCCESS = "PARENT_CATEGORY_EDIT_SUCCESS"
export const PARENT_CATEGORY_EDIT_FAIL = "PARENT_CATEGORY_EDIT_FAIL"
export const PARENT_CATEGORY_EDIT_RESET = "PARENT_CATEGORY_EDIT_RESET"

export const PARENT_CATEGORY_GET_DETAILS_REQUEST = "PARENT_CATEGORY_GET_DETAILS_REQUEST";
export const PARENT_CATEGORY_GET_DETAILS_SUCCESS = "PARENT_CATEGORY_GET_DETAILS_SUCCESS";
export const PARENT_CATEGORY_GET_DETAILS_FAIL = "PARENT_CATEGORY_GET_DETAILS_FAIL";
export const PARENT_CATEGORY_GET_DETAILS_RESET = "PARENT_CATEGORY_GET_DETAILS_RESET";

export const PARENT_CATEGORY_DELETE_REQUEST = "PARENT_CATEGORY_DELETE_REQUEST";
export const PARENT_CATEGORY_DELETE_SUCCESS = "PARENT_CATEGORY_DELETE_SUCCESS";
export const PARENT_CATEGORY_DELETE_FAIL = "PARENT_CATEGORY_DELETE_FAIL";