export const PERMISSION_LIST_REQUEST = "PERMISSION_LIST_REQUEST";
export const PERMISSION_LIST_SUCCESS = "PERMISSION_LIST_SUCCESS";
export const PERMISSION_LIST_FAIL = "PERMISSION_LIST_FAIL";
export const PERMISSION_LIST_RESET = "PERMISSION_LIST_RESET";

export const PERMISSION_EDIT_REQUEST = "PERMISSION_EDIT_REQUEST";
export const PERMISSION_EDIT_SUCCESS = "PERMISSION_EDIT_SUCCESS";
export const PERMISSION_EDIT_FAIL = "PERMISSION_EDIT_FAIL";
export const PERMISSION_EDIT_RESET = "PERMISSION_EDIT_RESET";

export const PERMISSION_CREATE_REQUEST = "PERMISSION_CREATE_REQUEST";
export const PERMISSION_CREATE_SUCCESS = "PERMISSION_CREATE_SUCCESS";
export const PERMISSION_CREATE_FAIL = "PERMISSION_CREATE_FAIL";
export const PERMISSION_CREATE_RESET = "PERMISSION_CREATE_RESET";

export const PERMISSION_GET_DETAILS_REQUEST = "PERMISSION_GET_DETAILS_REQUEST";
export const PERMISSION_GET_DETAILS_SUCCESS = "PERMISSION_GET_DETAILS_SUCCESS";
export const PERMISSION_GET_DETAILS_FAIL = "PERMISSION_GET_DETAILS_FAIL";
export const PERMISSION_GET_DETAILS_RESET = "PERMISSION_GET_DETAILS_RESET";

export const PERMISSION_DELETE_REQUEST = "PERMISSION_DELETE_REQUEST";
export const PERMISSION_DELETE_SUCCESS = "PERMISSION_DELETE_SUCCESS";
export const PERMISSION_DELETE_FAIL = "PERMISSION_DELETE_FAIL";