export const PRODUCT_ADMIN_LIST_REQUEST = "PRODUCT_ADMIN_LIST_REQUEST"
export const PRODUCT_ADMIN_LIST_SUCCESS = "PRODUCT_ADMIN_LIST_SUCCESS"
export const PRODUCT_ADMIN_LIST_FAIL = "PRODUCT_ADMIN_LIST_FAIL"
export const PRODUCT_ADMIN_LIST_RESET = "PRODUCT_ADMIN_LIST_RESET"

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";
export const PRODUCT_EDIT_RESET = "PRODUCT_EDIT_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_GET_DETAILS_REQUEST = "PRODUCT_GET_DETAILS_REQUEST";
export const PRODUCT_GET_DETAILS_SUCCESS = "PRODUCT_GET_DETAILS_SUCCESS";
export const PRODUCT_GET_DETAILS_FAIL = "PRODUCT_GET_DETAILS_FAIL";
export const PRODUCT_GET_DETAILS_RESET = "PRODUCT_GET_DETAILS_RESET";

export const PRODUCT_GET_REL_DETAILS_REQUEST = "PRODUCT_GET_REL_DETAILS_REQUEST";
export const PRODUCT_GET_REL_DETAILS_SUCCESS = "PRODUCT_GET_REL_DETAILS_SUCCESS";
export const PRODUCT_GET_REL_DETAILS_FAIL = "PRODUCT_GET_REL_DETAILS_FAIL";
export const PRODUCT_GET_REL_DETAILS_RESET = "PRODUCT_GET_REL_DETAILS_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_IMAGE_CREATE_REQUEST = "PRODUCT_IMAGE_CREATE_REQUEST";
export const PRODUCT_IMAGE_CREATE_SUCCESS = "PRODUCT_IMAGE_CREATE_SUCCESS";
export const PRODUCT_IMAGE_CREATE_FAIL = "PRODUCT_IMAGE_CREATE_FAIL";
export const PRODUCT_IMAGE_CREATE_RESET = "PRODUCT_IMAGE_CREATE_RESET";

export const PRODUCT_IMAGE_REPLACE_REQUEST = "PRODUCT_IMAGE_REPLACE_REQUEST";
export const PRODUCT_IMAGE_REPLACE_SUCCESS = "PRODUCT_IMAGE_REPLACE_SUCCESS";
export const PRODUCT_IMAGE_REPLACE_FAIL = "PRODUCT_IMAGE_REPLACE_FAIL";
export const PRODUCT_IMAGE_REPLACE_RESET = "PRODUCT_IMAGE_REPLACE_RESET";

export const PRODUCT_IMAGE_DELETE_REQUEST = "PRODUCT_IMAGE_DELETE_REQUEST";
export const PRODUCT_IMAGE_DELETE_SUCCESS = "PRODUCT_IMAGE_DELETE_SUCCESS";
export const PRODUCT_IMAGE_DELETE_FAIL = "PRODUCT_IMAGE_DELETE_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

// for public actions
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";