export const PRODUCT_ADMIN_LIST_REQUEST = "PRODUCT_ADMIN_LIST_REQUEST"
export const PRODUCT_ADMIN_LIST_SUCCESS = "PRODUCT_ADMIN_LIST_SUCCESS"
export const PRODUCT_ADMIN_LIST_FAIL = "PRODUCT_ADMIN_LIST_FAIL"
export const PRODUCT_ADMIN_LIST_RESET = "PRODUCT_ADMIN_LIST_RESET"