export const REVIEW_ADMIN_LIST_REQUEST = "REVIEW_ADMIN_LIST_REQUEST"
export const REVIEW_ADMIN_LIST_SUCCESS = "REVIEW_ADMIN_LIST_SUCCESS"
export const REVIEW_ADMIN_LIST_FAIL = "REVIEW_ADMIN_LIST_FAIL"
export const REVIEW_ADMIN_LIST_RESET = "REVIEW_ADMIN_LIST_RESET"

export const REVIEW_LIST_PAG_REQUEST = "REVIEW_LIST_PAG_REQUEST"
export const REVIEW_LIST_PAG_SUCCESS = "REVIEW_LIST_PAG_SUCCESS"
export const REVIEW_LIST_PAG_FAIL = "REVIEW_LIST_PAG_FAIL"
export const REVIEW_LIST_PAG_RESET = "REVIEW_LIST_PAG_RESET"

export const REVIEW_EDIT_REQUEST = "REVIEW_EDIT_REQUEST"
export const REVIEW_EDIT_SUCCESS = "REVIEW_EDIT_SUCCESS"
export const REVIEW_EDIT_FAIL = "REVIEW_EDIT_FAIL"
export const REVIEW_EDIT_RESET = "REVIEW_EDIT_RESET"

export const REVIEW_GET_DETAILS_REQUEST = "REVIEW_GET_DETAILS_REQUEST";
export const REVIEW_GET_DETAILS_SUCCESS = "REVIEW_GET_DETAILS_SUCCESS";
export const REVIEW_GET_DETAILS_FAIL = "REVIEW_GET_DETAILS_FAIL";
export const REVIEW_GET_DETAILS_RESET = "REVIEW_GET_DETAILS_RESET";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";