export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";
export const ROLE_LIST_RESET = "ROLE_LIST_RESET";

export const ROLE_EDIT_REQUEST = "ROLE_EDIT_REQUEST";
export const ROLE_EDIT_SUCCESS = "ROLE_EDIT_SUCCESS";
export const ROLE_EDIT_FAIL = "ROLE_EDIT_FAIL";
export const ROLE_EDIT_RESET = "ROLE_EDIT_RESET";

export const ROLE_CREATE_REQUEST = "ROLE_CREATE_REQUEST";
export const ROLE_CREATE_SUCCESS = "ROLE_CREATE_SUCCESS";
export const ROLE_CREATE_FAIL = "ROLE_CREATE_FAIL";
export const ROLE_CREATE_RESET = "ROLE_CREATE_RESET";

export const ROLE_GET_DETAILS_REQUEST = "ROLE_GET_DETAILS_REQUEST";
export const ROLE_GET_DETAILS_SUCCESS = "ROLE_GET_DETAILS_SUCCESS";
export const ROLE_GET_DETAILS_FAIL = "ROLE_GET_DETAILS_FAIL";
export const ROLE_GET_DETAILS_RESET = "ROLE_GET_DETAILS_RESET";

export const ROLE_DELETE_REQUEST = "ROLE_DELETE_REQUEST";
export const ROLE_DELETE_SUCCESS = "ROLE_DELETE_SUCCESS";
export const ROLE_DELETE_FAIL = "ROLE_DELETE_FAIL";