export const SIZE_ADMIN_LIST_REQUEST = "SIZE_ADMIN_LIST_REQUEST"
export const SIZE_ADMIN_LIST_SUCCESS = "SIZE_ADMIN_LIST_SUCCESS"
export const SIZE_ADMIN_LIST_FAIL = "SIZE_ADMIN_LIST_FAIL"
export const SIZE_ADMIN_LIST_RESET = "SIZE_ADMIN_LIST_RESET"

export const SIZE_CREATE_REQUEST = "SIZE_CREATE_REQUEST"
export const SIZE_CREATE_SUCCESS = "SIZE_CREATE_SUCCESS"
export const SIZE_CREATE_FAIL = "SIZE_CREATE_FAIL"
export const SIZE_CREATE_RESET = "SIZE_CREATE_RESET"

export const SIZE_EDIT_REQUEST = "SIZE_EDIT_REQUEST"
export const SIZE_EDIT_SUCCESS = "SIZE_EDIT_SUCCESS"
export const SIZE_EDIT_FAIL = "SIZE_EDIT_FAIL"
export const SIZE_EDIT_RESET = "SIZE_EDIT_RESET"

export const SIZE_GET_DETAILS_REQUEST = "SIZE_GET_DETAILS_REQUEST";
export const SIZE_GET_DETAILS_SUCCESS = "SIZE_GET_DETAILS_SUCCESS";
export const SIZE_GET_DETAILS_FAIL = "SIZE_GET_DETAILS_FAIL";
export const SIZE_GET_DETAILS_RESET = "SIZE_GET_DETAILS_RESET";

export const SIZE_DELETE_REQUEST = "SIZE_DELETE_REQUEST";
export const SIZE_DELETE_SUCCESS = "SIZE_DELETE_SUCCESS";
export const SIZE_DELETE_FAIL = "SIZE_DELETE_FAIL";