export const TYPE_ADMIN_LIST_REQUEST = "TYPE_ADMIN_LIST_REQUEST"
export const TYPE_ADMIN_LIST_SUCCESS = "TYPE_ADMIN_LIST_SUCCESS"
export const TYPE_ADMIN_LIST_FAIL = "TYPE_ADMIN_LIST_FAIL"
export const TYPE_ADMIN_LIST_RESET = "TYPE_ADMIN_LIST_RESET"

export const TYPE_CREATE_REQUEST = "TYPE_CREATE_REQUEST"
export const TYPE_CREATE_SUCCESS = "TYPE_CREATE_SUCCESS"
export const TYPE_CREATE_FAIL = "TYPE_CREATE_FAIL"
export const TYPE_CREATE_RESET = "TYPE_CREATE_RESET"

export const TYPE_EDIT_REQUEST = "TYPE_EDIT_REQUEST"
export const TYPE_EDIT_SUCCESS = "TYPE_EDIT_SUCCESS"
export const TYPE_EDIT_FAIL = "TYPE_EDIT_FAIL"
export const TYPE_EDIT_RESET = "TYPE_EDIT_RESET"

export const TYPE_GET_DETAILS_REQUEST = "TYPE_GET_DETAILS_REQUEST";
export const TYPE_GET_DETAILS_SUCCESS = "TYPE_GET_DETAILS_SUCCESS";
export const TYPE_GET_DETAILS_FAIL = "TYPE_GET_DETAILS_FAIL";
export const TYPE_GET_DETAILS_RESET = "TYPE_GET_DETAILS_RESET";

export const TYPE_DELETE_REQUEST = "TYPE_DELETE_REQUEST";
export const TYPE_DELETE_SUCCESS = "TYPE_DELETE_SUCCESS";
export const TYPE_DELETE_FAIL = "TYPE_DELETE_FAIL";