export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_RESET_PASS_REQUEST = "USER_RESET_PASS_REQUEST";
export const USER_RESET_PASS_SUCCESS = "USER_RESET_PASS_SUCCESS";
export const USER_RESET_PASS_FAIL = "USER_RESET_PASS_FAIL";
export const USER_RESET_PASS_RESET = "USER_RESET_PASS_RESET";

export const RESET_USER_REQUEST = "RESET_USER_REQUEST";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const RESET_USER_FAIL = "RESET_USER_FAIL";
export const RESET_USER_RESET = "RESET_USER_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";
export const USER_EDIT_RESET = "USER_EDIT_RESET";

export const USER_GET_DETAILS_REQUEST = "USER_GET_DETAILS_REQUEST";
export const USER_GET_DETAILS_SUCCESS = "USER_GET_DETAILS_SUCCESS";
export const USER_GET_DETAILS_FAIL = "USER_GET_DETAILS_FAIL";
export const USER_GET_DETAILS_RESET = "USER_GET_DETAILS_RESET";